---
title: Mon super blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: ''
baseurl: Heiisoo.github.io
url: ''
twitter_username: Heiisoo
github_username: Heiisoo
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
